# Generated by Django 2.0.5 on 2018-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_auto_20180903_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='leader_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
