# Generated by Django 2.0.5 on 2018-09-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_auto_20180903_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_complete',
        ),
    ]
