# Generated by Django 2.0.5 on 2018-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_remove_student_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uuid',
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.IntegerField(default=0, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
