# Generated by Django 2.0.5 on 2018-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0005_auto_20180905_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
