# Generated by Django 2.0.5 on 2018-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0006_auto_20180905_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
