# Generated by Django 2.0.5 on 2018-09-03 14:40

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0002_auto_20180903_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetypes', jsonfield.fields.JSONField()),
                ('motivalis', jsonfield.fields.JSONField()),
                ('levels', jsonfield.fields.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='context.Student')),
            ],
        ),
        migrations.CreateModel(
            name='UserDiagnosticsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.IsleContext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userdiagnosticsresults',
            unique_together={('user', 'context')},
        ),
    ]
