# Generated by Django 2.0.5 on 2018-09-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0006_auto_20180905_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkingRecommendationDeprecated',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recommendations', jsonfield.fields.JSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
                ('created', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='context.Student')),
            ],
        ),
    ]
