# Generated by Django 2.0.5 on 2018-10-01 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edu_common', '0001_initial'),
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkingInfoStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', jsonfield.fields.JSONField(default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
                ('updated', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_common.Student')),
            ],
        ),
    ]
