# Generated by Django 2.0.5 on 2018-09-03 10:08

import apps.core.models
import apps.core.raw_recommendation
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecommendationFresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.Student')),
            ],
            bases=(models.Model, apps.core.raw_recommendation.RawRecommendation, apps.core.models.MutableMixin),
        ),
        migrations.CreateModel(
            name='ActivityRecommendationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('source', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.Student')),
            ],
            bases=(models.Model, apps.core.raw_recommendation.RawRecommendation, apps.core.models.ImmutableMixin),
        ),
        migrations.AlterUniqueTogether(
            name='activityrecommendationlogs',
            unique_together={('user', 'item', 'created')},
        ),
        migrations.AlterUniqueTogether(
            name='activityrecommendationfresh',
            unique_together={('user', 'item')},
        ),
    ]
