# Generated by Django 2.0.5 on 2018-09-07 11:59

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleScoreComputeTask',
            fields=[
                ('input', jsonfield.fields.JSONField(default={})),
                ('output', jsonfield.fields.JSONField(default={})),
                ('complete', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.UUID('fa6a3cd5-4a23-4ad6-9342-55c1ca7caf2f'), primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='context.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
