# Generated by Django 2.0.5 on 2018-09-07 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlescorecomputetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f4545cce-f84f-4400-878b-9973d9e33019'), primary_key=True, serialize=False),
        ),
    ]
