# Generated by Django 2.0.5 on 2018-09-08 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0002_auto_20180907_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlescorecomputetask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
