# Generated by Django 2.0.5 on 2018-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0003_auto_20180908_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleQuestionIdUuidMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('ple_id', models.IntegerField()),
            ],
        ),
    ]
