# Generated by Django 2.0.5 on 2018-09-08 18:19

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0004_plequestioniduuidmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlescorecomputetask',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False),
        ),
    ]
